apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.2.0
    helm:
      values: |
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false

        prometheus:
          prometheusSpec:
            retention: 5d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1536Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: managed-csi
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi

        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: managed-csi
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi

        grafana:
          persistence:
            enabled: false
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
              label: grafana_dashboard
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki
              access: proxy
              url: http://loki.monitoring.svc.cluster.local:3100
              isDefault: false
              jsonData:
                maxLines: 1000
                timeout: 60

        prometheus-node-exporter:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi

        kube-state-metrics:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true